// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vopl3.h for the primary calling header

#ifndef VERILATED_VOPL3___024ROOT_H_
#define VERILATED_VOPL3___024ROOT_H_  // guard

#include "verilated.h"


class Vopl3__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vopl3___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(clk_host,0,0);
        VL_IN8(ic_n,0,0);
        CData/*0:0*/ opl3__DOT__host_if__DOT____Vcellinp__afifo__i_rd_reset_n;
        VL_IN8(clk_dac,0,0);
        VL_IN8(cs_n,0,0);
        VL_IN8(rd_n,0,0);
        VL_IN8(wr_n,0,0);
        VL_IN8(address,1,0);
        VL_IN8(din,7,0);
        VL_OUT8(dout,7,0);
        VL_OUT8(sample_valid,0,0);
        VL_OUT8(led,3,0);
        VL_OUT8(irq_n,0,0);
        VL_IN8(force_clear_flags,0,0);
        CData/*0:0*/ opl3__DOT__sample_clk_en;
        CData/*7:0*/ opl3__DOT__status;
        CData/*0:0*/ opl3__DOT__reset_sync__DOT__r0;
        CData/*0:0*/ opl3__DOT__reset_sync__DOT__r1;
        CData/*0:0*/ opl3__DOT__reset_sync__DOT__r2;
        CData/*0:0*/ opl3__DOT__host_if__DOT__cs_p1_n;
        CData/*0:0*/ opl3__DOT__host_if__DOT__wr_p1_n;
        CData/*1:0*/ opl3__DOT__host_if__DOT__address_p1;
        CData/*7:0*/ opl3__DOT__host_if__DOT__din_p1;
        CData/*0:0*/ opl3__DOT__host_if__DOT__opl3_fifo_empty;
        CData/*0:0*/ opl3__DOT__host_if__DOT__wr_p1;
        CData/*0:0*/ opl3__DOT__host_if__DOT__wr_p2;
        CData/*7:0*/ opl3__DOT__host_if__DOT__host_status_p1;
        CData/*0:0*/ opl3__DOT__host_if__DOT____Vcellinp__afifo__i_wr;
        CData/*0:0*/ opl3__DOT__host_if__DOT__afifo__DOT__o_wr_full;
        CData/*6:0*/ opl3__DOT__host_if__DOT__afifo__DOT__rd_addr;
        CData/*6:0*/ opl3__DOT__host_if__DOT__afifo__DOT__wr_addr;
        CData/*6:0*/ opl3__DOT__host_if__DOT__afifo__DOT__rd_wgray;
        CData/*6:0*/ opl3__DOT__host_if__DOT__afifo__DOT__wr_rgray;
        CData/*6:0*/ opl3__DOT__host_if__DOT__afifo__DOT__next_rd_addr;
        CData/*6:0*/ opl3__DOT__host_if__DOT__afifo__DOT__next_wr_addr;
        CData/*6:0*/ opl3__DOT__host_if__DOT__afifo__DOT__rgray;
        CData/*6:0*/ opl3__DOT__host_if__DOT__afifo__DOT__wgray;
        CData/*6:0*/ opl3__DOT__host_if__DOT__afifo__DOT__rgray_cross;
        CData/*6:0*/ opl3__DOT__host_if__DOT__afifo__DOT__wgray_cross;
        CData/*0:0*/ opl3__DOT__host_if__DOT__afifo__DOT__lcl_rd_empty;
        SData/*15:0*/ opl3__DOT__host_if__DOT__dout_sync__DOT__sync_regs;
        CData/*0:0*/ opl3__DOT__host_if__DOT__genblk1__DOT__trick_sw_detection__DOT__cs_p1_n;
        CData/*0:0*/ opl3__DOT__host_if__DOT__genblk1__DOT__trick_sw_detection__DOT__wr_p1_n;
        CData/*0:0*/ opl3__DOT__host_if__DOT__genblk1__DOT__trick_sw_detection__DOT__rd_p1_n;
        CData/*1:0*/ opl3__DOT__host_if__DOT__genblk1__DOT__trick_sw_detection__DOT__address_p1;
        CData/*7:0*/ opl3__DOT__host_if__DOT__genblk1__DOT__trick_sw_detection__DOT__din_p1;
        CData/*0:0*/ opl3__DOT__host_if__DOT__genblk1__DOT__trick_sw_detection__DOT__wr_p1;
        CData/*0:0*/ opl3__DOT__host_if__DOT__genblk1__DOT__trick_sw_detection__DOT__wr_p2;
        CData/*5:0*/ opl3__DOT__host_if__DOT__genblk1__DOT__trick_sw_detection__DOT__host_rd_counter;
        CData/*0:0*/ opl3__DOT__host_if__DOT__genblk1__DOT__trick_sw_detection__DOT__rd_p1;
        CData/*0:0*/ opl3__DOT__host_if__DOT__genblk1__DOT__trick_sw_detection__DOT__rd_p2;
        CData/*0:0*/ opl3__DOT__host_if__DOT__genblk1__DOT__trick_sw_detection__DOT__host_force_timer_overflow;
        CData/*0:0*/ opl3__DOT__host_if__DOT__genblk1__DOT__trick_sw_detection__DOT__start_counter;
        CData/*7:0*/ opl3__DOT__host_if__DOT__genblk1__DOT__trick_sw_detection__DOT__timer1;
        CData/*1:0*/ opl3__DOT__host_if__DOT__genblk1__DOT__trick_sw_detection__DOT__force_timer_overflow_sync__DOT__sync_regs;
        CData/*0:0*/ opl3__DOT__channels__DOT__channel_valid;
        CData/*0:0*/ opl3__DOT__channels__DOT__ops_done_pulse;
        CData/*5:0*/ opl3__DOT__channels__DOT__connection_sel;
        CData/*0:0*/ opl3__DOT__channels__DOT__is_new;
        CData/*0:0*/ opl3__DOT__channels__DOT__ryt;
        CData/*7:0*/ opl3__DOT__channels__DOT____Vcellout__ch_abcd_cnt_mem__dob;
        CData/*7:0*/ opl3__DOT__channels__DOT__ch_abcd_cnt_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank__DOT____Vlvbound_h86a57974__0;
        CData/*7:0*/ opl3__DOT__channels__DOT__ch_abcd_cnt_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank__DOT____Vlvbound_h86a57974__0;
    };
    struct {
        CData/*1:0*/ opl3__DOT__channels__DOT__control_operators__DOT__delay_counter;
        CData/*5:0*/ opl3__DOT__channels__DOT__control_operators__DOT__state;
        CData/*5:0*/ opl3__DOT__channels__DOT__control_operators__DOT__next_state;
        CData/*0:0*/ opl3__DOT__channels__DOT__control_operators__DOT__bank_num_p1;
        CData/*4:0*/ opl3__DOT__channels__DOT__control_operators__DOT__op_num;
        CData/*4:0*/ opl3__DOT__channels__DOT__control_operators__DOT__op_num_p1;
        CData/*0:0*/ opl3__DOT__channels__DOT__control_operators__DOT__use_feedback_p1;
        CData/*0:0*/ opl3__DOT__channels__DOT__control_operators__DOT__op_sample_clk_en;
        CData/*5:0*/ opl3__DOT__channels__DOT__control_operators__DOT__bank_num_p;
        IData/*29:0*/ opl3__DOT__channels__DOT__control_operators__DOT__op_num_p;
        CData/*5:0*/ opl3__DOT__channels__DOT__control_operators__DOT__connection_sel_p1;
        CData/*0:0*/ opl3__DOT__channels__DOT__control_operators__DOT__ryt_p1;
        CData/*3:0*/ opl3__DOT__channels__DOT__control_operators__DOT__kon_block_fnum_channel_mem_rd_address;
        CData/*3:0*/ opl3__DOT__channels__DOT__control_operators__DOT__fb_cnt0_channel_mem_rd_address;
        CData/*3:0*/ opl3__DOT__channels__DOT__control_operators__DOT__cnt1_channel_mem_rd_address;
        CData/*0:0*/ opl3__DOT__channels__DOT__control_operators__DOT__nts;
        CData/*0:0*/ opl3__DOT__channels__DOT__control_operators__DOT__dvb;
        CData/*0:0*/ opl3__DOT__channels__DOT__control_operators__DOT__dam;
        CData/*0:0*/ opl3__DOT__channels__DOT__control_operators__DOT__bd;
        CData/*0:0*/ opl3__DOT__channels__DOT__control_operators__DOT__sd;
        CData/*0:0*/ opl3__DOT__channels__DOT__control_operators__DOT__tom;
        CData/*0:0*/ opl3__DOT__channels__DOT__control_operators__DOT__tc;
        CData/*0:0*/ opl3__DOT__channels__DOT__control_operators__DOT__hh;
        CData/*7:0*/ opl3__DOT__channels__DOT__control_operators__DOT____Vcellout__am_vib_egt_ksr_mult_mem__dob;
        CData/*0:0*/ opl3__DOT__channels__DOT__control_operators__DOT____Vcellinp__am_vib_egt_ksr_mult_mem__wea;
        CData/*7:0*/ opl3__DOT__channels__DOT__control_operators__DOT____Vcellout__ksl_tl_mem__dob;
        CData/*0:0*/ opl3__DOT__channels__DOT__control_operators__DOT____Vcellinp__ksl_tl_mem__wea;
        CData/*0:0*/ opl3__DOT__channels__DOT__control_operators__DOT____Vcellinp__ar_dr_mem__wea;
        CData/*7:0*/ opl3__DOT__channels__DOT__control_operators__DOT____Vcellout__sl_rr_mem__dob;
        CData/*0:0*/ opl3__DOT__channels__DOT__control_operators__DOT____Vcellinp__sl_rr_mem__wea;
        CData/*0:0*/ opl3__DOT__channels__DOT__control_operators__DOT____Vcellinp__ws_mem__wea;
        CData/*7:0*/ opl3__DOT__channels__DOT__control_operators__DOT____Vcellout__fnum_low_mem__dob;
        CData/*0:0*/ opl3__DOT__channels__DOT__control_operators__DOT____Vcellinp__fnum_low_mem__wea;
        CData/*4:0*/ opl3__DOT__channels__DOT__control_operators__DOT____Vcellout__block_fnum_high_mem__dob;
        CData/*5:0*/ opl3__DOT__channels__DOT__control_operators__DOT____Vcellout__sample_clk_en_sr__out;
        CData/*7:0*/ opl3__DOT__channels__DOT__control_operators__DOT__am_vib_egt_ksr_mult_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank__DOT____Vlvbound_h78e36339__0;
        CData/*7:0*/ opl3__DOT__channels__DOT__control_operators__DOT__am_vib_egt_ksr_mult_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank__DOT____Vlvbound_h78e36339__0;
        CData/*7:0*/ opl3__DOT__channels__DOT__control_operators__DOT__ksl_tl_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank__DOT____Vlvbound_h78e36339__0;
        CData/*7:0*/ opl3__DOT__channels__DOT__control_operators__DOT__ksl_tl_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank__DOT____Vlvbound_h78e36339__0;
        CData/*7:0*/ opl3__DOT__channels__DOT__control_operators__DOT__ar_dr_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank__DOT____Vlvbound_h78e36339__0;
        CData/*7:0*/ opl3__DOT__channels__DOT__control_operators__DOT__ar_dr_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank__DOT____Vlvbound_h78e36339__0;
        CData/*7:0*/ opl3__DOT__channels__DOT__control_operators__DOT__sl_rr_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank__DOT____Vlvbound_h78e36339__0;
        CData/*7:0*/ opl3__DOT__channels__DOT__control_operators__DOT__sl_rr_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank__DOT____Vlvbound_h78e36339__0;
        CData/*2:0*/ opl3__DOT__channels__DOT__control_operators__DOT__ws_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank__DOT____Vlvbound_hebd03cde__0;
        CData/*2:0*/ opl3__DOT__channels__DOT__control_operators__DOT__ws_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank__DOT____Vlvbound_hebd03cde__0;
        CData/*7:0*/ opl3__DOT__channels__DOT__control_operators__DOT__fnum_low_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank__DOT____Vlvbound_h86a57974__0;
        CData/*7:0*/ opl3__DOT__channels__DOT__control_operators__DOT__fnum_low_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank__DOT____Vlvbound_h86a57974__0;
        CData/*5:0*/ opl3__DOT__channels__DOT__control_operators__DOT__kon_mem__DOT__self;
        CData/*5:0*/ opl3__DOT__channels__DOT__control_operators__DOT__kon_mem__DOT__next_self;
        CData/*0:0*/ opl3__DOT__channels__DOT__control_operators__DOT__kon_mem__DOT____Vcellinp__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank__dia;
        CData/*3:0*/ opl3__DOT__channels__DOT__control_operators__DOT__kon_mem__DOT____Vcellinp__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank__addra;
        CData/*0:0*/ opl3__DOT__channels__DOT__control_operators__DOT__kon_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank__DOT____Vlvbound_hecc6a027__0;
        CData/*0:0*/ opl3__DOT__channels__DOT__control_operators__DOT__kon_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank__DOT____Vlvbound_hecc6a027__0;
        CData/*0:0*/ opl3__DOT__channels__DOT__control_operators__DOT__block_fnum_high_mem__DOT____Vcellinp__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank__wea;
        CData/*0:0*/ opl3__DOT__channels__DOT__control_operators__DOT__block_fnum_high_mem__DOT____Vcellinp__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank__wea;
        CData/*4:0*/ opl3__DOT__channels__DOT__control_operators__DOT__block_fnum_high_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank__DOT____Vlvbound_hf28499db__0;
        CData/*4:0*/ opl3__DOT__channels__DOT__control_operators__DOT__block_fnum_high_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank__DOT____Vlvbound_hf28499db__0;
        CData/*1:0*/ opl3__DOT__channels__DOT__control_operators__DOT__fb_cnt0_mem__DOT__bankb_p;
        CData/*0:0*/ opl3__DOT__channels__DOT__control_operators__DOT__fb_cnt0_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__reb_mem;
        CData/*0:0*/ opl3__DOT__channels__DOT__control_operators__DOT__fb_cnt0_mem__DOT____Vcellinp__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank__wea;
        CData/*0:0*/ opl3__DOT__channels__DOT__control_operators__DOT__fb_cnt0_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__reb_mem;
        CData/*0:0*/ opl3__DOT__channels__DOT__control_operators__DOT__fb_cnt0_mem__DOT____Vcellinp__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank__wea;
        CData/*3:0*/ opl3__DOT__channels__DOT__control_operators__DOT__fb_cnt0_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank__DOT__genblk1__DOT__dob_p1;
        CData/*3:0*/ opl3__DOT__channels__DOT__control_operators__DOT__fb_cnt0_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank__DOT____Vlvbound_h95153f4e__0;
    };
    struct {
        CData/*3:0*/ opl3__DOT__channels__DOT__control_operators__DOT__fb_cnt0_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank__DOT__genblk1__DOT__dob_p1;
        CData/*3:0*/ opl3__DOT__channels__DOT__control_operators__DOT__fb_cnt0_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank__DOT____Vlvbound_h95153f4e__0;
        CData/*1:0*/ opl3__DOT__channels__DOT__control_operators__DOT__fb_cnt1_mem__DOT__bankb_p;
        CData/*0:0*/ opl3__DOT__channels__DOT__control_operators__DOT__fb_cnt1_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank__DOT__genblk1__DOT__dob_p1;
        CData/*0:0*/ opl3__DOT__channels__DOT__control_operators__DOT__fb_cnt1_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank__DOT____Vlvbound_hecc6a027__0;
        CData/*0:0*/ opl3__DOT__channels__DOT__control_operators__DOT__fb_cnt1_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank__DOT__genblk1__DOT__dob_p1;
        CData/*0:0*/ opl3__DOT__channels__DOT__control_operators__DOT__fb_cnt1_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank__DOT____Vlvbound_hecc6a027__0;
        CData/*5:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__bank_num_p;
        IData/*29:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__op_num_p;
        CData/*2:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__op_type_p0;
        CData/*0:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__key_on_p0;
        CData/*5:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT____Vcellout__sample_clk_en_sr__out;
        CData/*2:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__calc_phase_inc__DOT__vib_val_p2;
        CData/*4:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__calc_phase_inc__DOT__multiplier_p1;
        CData/*1:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__calc_phase_inc__DOT____Vcellout__vib_sr__out;
        CData/*2:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__calc_phase_inc__DOT__vibrato__DOT__delta2_p1;
        CData/*0:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__calc_phase_inc__DOT__vibrato__DOT__dvb_p1;
        CData/*3:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__state_p1;
        CData/*3:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__state_p2;
        CData/*3:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__next_state_p2;
        CData/*3:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__state_p3;
        CData/*7:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__ksl_add_p2;
        CData/*5:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__am_val_p2;
        CData/*3:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__requested_rate_p0;
        CData/*1:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__env_shift_p2;
        CData/*3:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__rate_hi_p2;
        CData/*0:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__eg_reset_p0;
        CData/*2:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__bank_num_p;
        SData/*14:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__op_num_p;
        IData/*17:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__tl_p;
        SData/*11:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__sl_p;
        CData/*2:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT____Vcellout__sample_clk_en_sr__out;
        CData/*2:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT____Vcellout__key_on_sr__out;
        CData/*2:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT____Vcellout__eg_reset_sr__out;
        CData/*3:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT____Vcellout__state_mem__dob;
        CData/*6:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__ksl_add_rom__DOT__rom_out_p1;
        CData/*5:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__ksl_add_rom__DOT__tmp0_p1;
        CData/*7:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__ksl_add_rom__DOT__tmp1_p1;
        CData/*1:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__ksl_add_rom__DOT__ksl_p1;
        CData/*3:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__state_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank__DOT____Vlvbound_hb6861da5__0;
        CData/*3:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__state_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank__DOT____Vlvbound_hb6861da5__0;
        CData/*0:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__calc_envelope_shift__DOT__eg_state;
        CData/*3:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__calc_envelope_shift__DOT__eg_add;
        CData/*3:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__calc_envelope_shift__DOT__ks_p0;
        CData/*6:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__calc_envelope_shift__DOT__rate_p1;
        CData/*3:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__calc_envelope_shift__DOT__rate_hi_p1;
        CData/*1:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__calc_envelope_shift__DOT__rate_lo_p1;
        CData/*1:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__calc_envelope_shift__DOT__eg_timer_lo;
        CData/*5:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__calc_envelope_shift__DOT__eg_shift_p1;
        CData/*0:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__calc_envelope_shift__DOT__requested_rate_not_zero_p1;
        CData/*2:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__calc_envelope_shift__DOT__env_shift_pre_p1;
        CData/*2:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__calc_envelope_shift__DOT__bank_num_p;
        SData/*14:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__calc_envelope_shift__DOT__op_num_p;
        CData/*2:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__calc_envelope_shift__DOT____Vcellout__sample_clk_en_sr__out;
        CData/*0:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__env_int_mem__DOT____Vcellinp__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank__wea;
        CData/*0:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__env_int_mem__DOT____Vcellinp__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank__wea;
        CData/*5:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__tremolo__DOT__am_val_tmp1_p1;
        CData/*0:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__tremolo__DOT__dam_p1;
        CData/*7:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__phase_generator__DOT__theta_p3;
        CData/*2:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__phase_generator__DOT__ws_post_opl_p0;
        IData/*17:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__phase_generator__DOT__ws_post_opl_p;
        CData/*5:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__phase_generator__DOT__bank_num_p;
        IData/*29:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__phase_generator__DOT__op_num_p;
        CData/*5:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__phase_generator__DOT____Vcellout__sample_clk_en_sr__out;
    };
    struct {
        CData/*1:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__phase_generator__DOT__phase_acc_mem__DOT__bankb_p;
        CData/*0:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__phase_generator__DOT__calc_rhythm_phase__DOT__rm_xor_p2;
        SData/*8:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__phase_generator__DOT__calc_rhythm_phase__DOT__op_type_p;
        CData/*2:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__phase_generator__DOT__calc_rhythm_phase__DOT__bank_num_p;
        SData/*14:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__phase_generator__DOT__calc_rhythm_phase__DOT__op_num_p;
        CData/*2:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__phase_generator__DOT__calc_rhythm_phase__DOT____Vcellout__sample_clk_en_sr__out;
        CData/*1:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__feedback_mem__DOT__bankb_p;
        CData/*1:0*/ opl3__DOT__channels__DOT__operator_out_mem__DOT__bankb_p;
        CData/*0:0*/ opl3__DOT__channels__DOT__dac_prep__DOT__sample_valid_opl3_p1;
        CData/*7:0*/ opl3__DOT__genblk1__DOT__timers__DOT__timer1;
        CData/*7:0*/ opl3__DOT__genblk1__DOT__timers__DOT__timer2;
        CData/*0:0*/ opl3__DOT__genblk1__DOT__timers__DOT__irq_rst;
        CData/*0:0*/ opl3__DOT__genblk1__DOT__timers__DOT__mt1;
        CData/*0:0*/ opl3__DOT__genblk1__DOT__timers__DOT__mt2;
        CData/*0:0*/ opl3__DOT__genblk1__DOT__timers__DOT__st1;
        CData/*0:0*/ opl3__DOT__genblk1__DOT__timers__DOT__st2;
        CData/*0:0*/ opl3__DOT__genblk1__DOT__timers__DOT__timer1_overflow_pulse;
        CData/*0:0*/ opl3__DOT__genblk1__DOT__timers__DOT__timer2_overflow_pulse;
        CData/*0:0*/ opl3__DOT__genblk1__DOT__timers__DOT__ft1;
        CData/*0:0*/ opl3__DOT__genblk1__DOT__timers__DOT__ft2;
        CData/*0:0*/ opl3__DOT__genblk1__DOT__timers__DOT__irq;
        CData/*0:0*/ opl3__DOT__genblk1__DOT__timers__DOT__timer1_inst__DOT__tick_pulse;
        CData/*7:0*/ opl3__DOT__genblk1__DOT__timers__DOT__timer1_inst__DOT__timer;
        CData/*0:0*/ opl3__DOT__genblk1__DOT__timers__DOT__timer1_inst__DOT__start_timer_set_pulse;
        CData/*0:0*/ opl3__DOT__genblk1__DOT__timers__DOT__timer1_inst__DOT__start_timer_edge_detect__DOT__in_r0;
        CData/*0:0*/ opl3__DOT__genblk1__DOT__timers__DOT__timer2_inst__DOT__tick_pulse;
        CData/*7:0*/ opl3__DOT__genblk1__DOT__timers__DOT__timer2_inst__DOT__timer;
        CData/*0:0*/ opl3__DOT__genblk1__DOT__timers__DOT__timer2_inst__DOT__start_timer_set_pulse;
        CData/*0:0*/ opl3__DOT__genblk1__DOT__timers__DOT__timer2_inst__DOT__start_timer_edge_detect__DOT__in_r0;
        CData/*7:0*/ __Vtrigprevexpr___TOP__opl3__DOT__channels__DOT____Vcellout__ch_abcd_cnt_mem__dob__0;
        CData/*0:0*/ __VstlDidInit;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*7:0*/ __Vtrigprevexpr___TOP__opl3__DOT__channels__DOT____Vcellout__ch_abcd_cnt_mem__dob__1;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__ic_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk_host__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__opl3__DOT__host_if__DOT____Vcellinp__afifo__i_rd_reset_n__0;
        CData/*0:0*/ __VactDidInit;
        CData/*0:0*/ __VactContinue;
        SData/*9:0*/ opl3__DOT__host_if__DOT____Vcellout__afifo__o_rd_data;
        SData/*9:0*/ opl3__DOT__sample_clk_gen__DOT__counter;
        SData/*12:0*/ opl3__DOT__channels__DOT__operator_mem_out;
        SData/*15:0*/ opl3__DOT__channels__DOT__channel_l;
        SData/*15:0*/ opl3__DOT__channels__DOT__channel_r;
        SData/*12:0*/ opl3__DOT__channels__DOT__control_operators__DOT__modulation_p1;
        SData/*12:0*/ opl3__DOT__channels__DOT__control_operators__DOT__out_p6;
        SData/*12:0*/ opl3__DOT__channels__DOT__control_operators__DOT__modulation_out_p1;
        SData/*9:0*/ opl3__DOT__channels__DOT__control_operators__DOT__fnum;
        SData/*10:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__env_p3;
        SData/*12:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__feedback_result_p1;
        SData/*12:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__calc_phase_inc__DOT__vibrato__DOT__vibrato_index_p1;
        SData/*9:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__calc_phase_inc__DOT__vibrato__DOT__fnum_p1;
        SData/*8:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__env_int_pre_p2;
        SData/*8:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__eg_inc_p2;
        SData/*8:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__env_int_new_p3;
        IData/*26:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__env_int_p;
        SData/*12:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__calc_envelope_shift__DOT__eg_timer;
        SData/*8:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__env_int_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank__DOT____Vlvbound_hb6d43ef3__0;
        SData/*8:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__env_int_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank__DOT____Vlvbound_hb6d43ef3__0;
        SData/*13:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__tremolo__DOT__tremolo_index_p1;
        SData/*9:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__phase_generator__DOT__final_phase_p3;
        SData/*9:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__phase_generator__DOT__rhythm_phase_p3;
        SData/*11:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__phase_generator__DOT__log_sin_out_p4;
        SData/*12:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__phase_generator__DOT__pre_gain_p4;
    };
    struct {
        SData/*14:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__phase_generator__DOT__post_gain_p4;
        VlWide<3>/*64:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__phase_generator__DOT__modulation_p;
        IData/*29:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__phase_generator__DOT__final_phase_p;
        SData/*13:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__phase_generator__DOT__env_shifted_p4;
        SData/*12:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__phase_generator__DOT__level_p4;
        SData/*12:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__phase_generator__DOT__level_p5;
        SData/*9:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__phase_generator__DOT__exp_out_p5;
        SData/*12:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__phase_generator__DOT__neg_p5;
        SData/*9:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__phase_generator__DOT__calc_rhythm_phase__DOT__hh_phase_friend;
        SData/*9:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__phase_generator__DOT__calc_rhythm_phase__DOT__tc_phase_friend;
        SData/*9:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__phase_generator__DOT__calc_rhythm_phase__DOT__hh_phase_p2;
        SData/*12:0*/ opl3__DOT__channels__DOT__operator_out_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank__DOT__genblk1__DOT__dob_p1;
        SData/*12:0*/ opl3__DOT__channels__DOT__operator_out_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank__DOT____Vlvbound_h1f1451d1__0;
        SData/*12:0*/ opl3__DOT__channels__DOT__operator_out_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank__DOT__genblk1__DOT__dob_p1;
        SData/*12:0*/ opl3__DOT__channels__DOT__operator_out_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank__DOT____Vlvbound_h1f1451d1__0;
        SData/*11:0*/ opl3__DOT__genblk1__DOT__timers__DOT__timer1_inst__DOT__tick_counter;
        SData/*13:0*/ opl3__DOT__genblk1__DOT__timers__DOT__timer2_inst__DOT__tick_counter;
        VL_OUT(sample_l,23,0);
        VL_OUT(sample_r,23,0);
        IData/*17:0*/ opl3__DOT__opl3_reg_wr;
        IData/*17:0*/ opl3__DOT__host_if__DOT__genblk1__DOT__trick_sw_detection__DOT__host_reg_wr;
        IData/*19:0*/ opl3__DOT__channels__DOT__operator_out;
        IData/*31:0*/ opl3__DOT__channels__DOT__state;
        IData/*31:0*/ opl3__DOT__channels__DOT__next_state;
        IData/*29:0*/ opl3__DOT__channels__DOT__signals;
        IData/*31:0*/ opl3__DOT__channels__DOT__control_operators__DOT__kon_mem__DOT__state;
        IData/*31:0*/ opl3__DOT__channels__DOT__control_operators__DOT__kon_mem__DOT__next_state;
        IData/*25:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT____Vcellout__feedback_mem__dob;
        IData/*25:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT____Vcellinp__feedback_mem__dia;
        VlWide<5>/*129:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT____Vcellout__feedback_sr__out;
        IData/*16:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__calc_phase_inc__DOT__pre_mult_p1;
        IData/*19:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__calc_phase_inc__DOT__post_mult_p2;
        IData/*19:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__phase_generator__DOT__phase_acc_p2;
        IData/*19:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__phase_generator__DOT__phase_acc_p3;
        IData/*19:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__phase_generator__DOT__phase_acc_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank__DOT__genblk1__DOT__dob_p1;
        IData/*19:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__phase_generator__DOT__phase_acc_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank__DOT__genblk1__DOT__genblk1__DOT__dob_p2;
        IData/*19:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__phase_generator__DOT__phase_acc_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank__DOT____Vlvbound_hbe76e32b__0;
        IData/*19:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__phase_generator__DOT__phase_acc_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank__DOT__genblk1__DOT__dob_p1;
        IData/*19:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__phase_generator__DOT__phase_acc_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank__DOT__genblk1__DOT__genblk1__DOT__dob_p2;
        IData/*19:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__phase_generator__DOT__phase_acc_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank__DOT____Vlvbound_hbe76e32b__0;
        IData/*23:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__phase_generator__DOT__calc_rhythm_phase__DOT__rand_num;
        IData/*25:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__feedback_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank__DOT__genblk1__DOT__dob_p1;
        IData/*25:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__feedback_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank__DOT____Vlvbound_hbc745659__0;
        IData/*25:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__feedback_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank__DOT__genblk1__DOT__dob_p1;
        IData/*25:0*/ opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__feedback_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank__DOT____Vlvbound_hbc745659__0;
        IData/*23:0*/ opl3__DOT__channels__DOT__dac_prep__DOT__sample_opl3_l_p1;
        IData/*23:0*/ opl3__DOT__channels__DOT__dac_prep__DOT__sample_opl3_r_p1;
        IData/*31:0*/ __VactIterCount;
        VlWide<3>/*76:0*/ opl3__DOT__channels__DOT__self;
        VlWide<3>/*76:0*/ opl3__DOT__channels__DOT__next_self;
        VlUnpacked<SData/*9:0*/, 64> opl3__DOT__host_if__DOT__afifo__DOT__mem;
        VlUnpacked<CData/*7:0*/, 2> opl3__DOT__channels__DOT__ch_abcd_cnt_mem__DOT__dob_array;
        VlUnpacked<CData/*7:0*/, 9> opl3__DOT__channels__DOT__ch_abcd_cnt_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank__DOT__ram;
        VlUnpacked<CData/*7:0*/, 9> opl3__DOT__channels__DOT__ch_abcd_cnt_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank__DOT__ram;
        VlUnpacked<CData/*7:0*/, 2> opl3__DOT__channels__DOT__control_operators__DOT__am_vib_egt_ksr_mult_mem__DOT__dob_array;
        VlUnpacked<CData/*7:0*/, 22> opl3__DOT__channels__DOT__control_operators__DOT__am_vib_egt_ksr_mult_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank__DOT__ram;
        VlUnpacked<CData/*7:0*/, 22> opl3__DOT__channels__DOT__control_operators__DOT__am_vib_egt_ksr_mult_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank__DOT__ram;
        VlUnpacked<CData/*7:0*/, 2> opl3__DOT__channels__DOT__control_operators__DOT__ksl_tl_mem__DOT__dob_array;
        VlUnpacked<CData/*7:0*/, 22> opl3__DOT__channels__DOT__control_operators__DOT__ksl_tl_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank__DOT__ram;
        VlUnpacked<CData/*7:0*/, 22> opl3__DOT__channels__DOT__control_operators__DOT__ksl_tl_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank__DOT__ram;
        VlUnpacked<CData/*7:0*/, 2> opl3__DOT__channels__DOT__control_operators__DOT__ar_dr_mem__DOT__dob_array;
        VlUnpacked<CData/*7:0*/, 22> opl3__DOT__channels__DOT__control_operators__DOT__ar_dr_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank__DOT__ram;
        VlUnpacked<CData/*7:0*/, 22> opl3__DOT__channels__DOT__control_operators__DOT__ar_dr_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank__DOT__ram;
        VlUnpacked<CData/*7:0*/, 2> opl3__DOT__channels__DOT__control_operators__DOT__sl_rr_mem__DOT__dob_array;
    };
    struct {
        VlUnpacked<CData/*7:0*/, 22> opl3__DOT__channels__DOT__control_operators__DOT__sl_rr_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank__DOT__ram;
        VlUnpacked<CData/*7:0*/, 22> opl3__DOT__channels__DOT__control_operators__DOT__sl_rr_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank__DOT__ram;
        VlUnpacked<CData/*2:0*/, 2> opl3__DOT__channels__DOT__control_operators__DOT__ws_mem__DOT__dob_array;
        VlUnpacked<CData/*2:0*/, 22> opl3__DOT__channels__DOT__control_operators__DOT__ws_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank__DOT__ram;
        VlUnpacked<CData/*2:0*/, 22> opl3__DOT__channels__DOT__control_operators__DOT__ws_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank__DOT__ram;
        VlUnpacked<CData/*7:0*/, 2> opl3__DOT__channels__DOT__control_operators__DOT__fnum_low_mem__DOT__dob_array;
        VlUnpacked<CData/*7:0*/, 9> opl3__DOT__channels__DOT__control_operators__DOT__fnum_low_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank__DOT__ram;
        VlUnpacked<CData/*7:0*/, 9> opl3__DOT__channels__DOT__control_operators__DOT__fnum_low_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank__DOT__ram;
        VlUnpacked<CData/*0:0*/, 2> opl3__DOT__channels__DOT__control_operators__DOT__kon_mem__DOT__dob_array;
        VlUnpacked<CData/*0:0*/, 9> opl3__DOT__channels__DOT__control_operators__DOT__kon_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank__DOT__ram;
        VlUnpacked<CData/*0:0*/, 9> opl3__DOT__channels__DOT__control_operators__DOT__kon_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank__DOT__ram;
        VlUnpacked<CData/*4:0*/, 2> opl3__DOT__channels__DOT__control_operators__DOT__block_fnum_high_mem__DOT__dob_array;
        VlUnpacked<CData/*4:0*/, 9> opl3__DOT__channels__DOT__control_operators__DOT__block_fnum_high_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank__DOT__ram;
        VlUnpacked<CData/*4:0*/, 9> opl3__DOT__channels__DOT__control_operators__DOT__block_fnum_high_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank__DOT__ram;
        VlUnpacked<CData/*3:0*/, 2> opl3__DOT__channels__DOT__control_operators__DOT__fb_cnt0_mem__DOT__dob_array;
        VlUnpacked<CData/*3:0*/, 9> opl3__DOT__channels__DOT__control_operators__DOT__fb_cnt0_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank__DOT__ram;
        VlUnpacked<CData/*3:0*/, 9> opl3__DOT__channels__DOT__control_operators__DOT__fb_cnt0_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank__DOT__ram;
        VlUnpacked<CData/*0:0*/, 2> opl3__DOT__channels__DOT__control_operators__DOT__fb_cnt1_mem__DOT__dob_array;
        VlUnpacked<CData/*0:0*/, 9> opl3__DOT__channels__DOT__control_operators__DOT__fb_cnt1_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank__DOT__ram;
        VlUnpacked<CData/*0:0*/, 9> opl3__DOT__channels__DOT__control_operators__DOT__fb_cnt1_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank__DOT__ram;
        VlUnpacked<CData/*3:0*/, 2> opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__state_mem__DOT__dob_array;
        VlUnpacked<CData/*3:0*/, 18> opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__state_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank__DOT__ram;
        VlUnpacked<CData/*3:0*/, 18> opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__state_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank__DOT__ram;
        VlUnpacked<SData/*8:0*/, 2> opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__env_int_mem__DOT__dob_array;
        VlUnpacked<SData/*8:0*/, 18> opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__env_int_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank__DOT__ram;
        VlUnpacked<SData/*8:0*/, 18> opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__env_int_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank__DOT__ram;
        VlUnpacked<IData/*19:0*/, 2> opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__phase_generator__DOT__phase_acc_mem__DOT__dob_array;
        VlUnpacked<IData/*19:0*/, 18> opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__phase_generator__DOT__phase_acc_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank__DOT__ram;
        VlUnpacked<IData/*19:0*/, 18> opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__phase_generator__DOT__phase_acc_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank__DOT__ram;
        VlUnpacked<IData/*25:0*/, 2> opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__feedback_mem__DOT__dob_array;
        VlUnpacked<IData/*25:0*/, 18> opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__feedback_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank__DOT__ram;
        VlUnpacked<IData/*25:0*/, 18> opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__feedback_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank__DOT__ram;
        VlUnpacked<SData/*12:0*/, 2> opl3__DOT__channels__DOT__operator_out_mem__DOT__dob_array;
        VlUnpacked<SData/*12:0*/, 18> opl3__DOT__channels__DOT__operator_out_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank__DOT__ram;
        VlUnpacked<SData/*12:0*/, 18> opl3__DOT__channels__DOT__operator_out_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank__DOT__ram;
    };
    VlTriggerVec<2> __VstlTriggered;
    VlTriggerVec<6> __VactTriggered;
    VlTriggerVec<6> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vopl3__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vopl3___024root(Vopl3__Syms* symsp, const char* v__name);
    ~Vopl3___024root();
    VL_UNCOPYABLE(Vopl3___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
